---
instances:
    - name: appserver1
      type: appserver
      subdomain: appserver1
    - name: appserver2
      type: appserver
      subdomain: appserver2
    - name: database
      type: database
    - name: loadbalancer
      type: loadbalancer
      subdomain: www

relative_names:
    - name: www # www.<domain>
    - name: "@" # so <domain> works as a URL. Otherwise only www.<domain> would work.
