groups:
  - name: microblog-test
    rules:
    - alert: MicroblogErrorDetected
      expr: flask_http_request_errors_total > 0
      for: 5s

  - name: More get requests than 20
    rules:
      - alert: between20and25
        expr: flask_http_request_total{method="GET",status="200"} > 20 and flask_http_request_total{method="GET",status="200"} < 25
        for: 10s