---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-OSAY21-DV1673-H25-LP2
domain_name: osay21.me

admin_email: osay21@student.bth.se

vmtags:
    StudentId: osay21 


pub_ssh_key_location: '/home/osay21/.ssh/devops.pub'


server_user: "deploy"
server_user_pass: "osay21"
server_user_groups:
    -   sudo
