# syntax=docker/dockerfile:1.4
FROM python:3.12-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=microblog.py

RUN <<-EOF
    chmod +x boot.sh
    chown -R microblog:microblog ./
EOF

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]