apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: default
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc.cluster.local
  ports:
    - port: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: ExternalName
  externalName: prometheus.monitoring.svc.cluster.local
  ports:
    - port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
spec:
  type: ExternalName
  externalName: alertmanager.monitoring.svc.cluster.local
  ports:
    - port: 9093