name: CI Pipeline

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  security:
    needs: tests
    uses: ./.github/workflows/security.yml