name: Deploy microblog

on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/devops
          chmod 600 ~/.ssh/devops

      - name: Deploy with Ansible
        run: |
          export ANSIBLE_PRIVATE_KEY_FILE=~/.ssh/devops
          export ANSIBLE_HOST_KEY_CHECKING=False

          echo "Deploying Microblog to static inventory..."
          ansible-playbook ansible/microblog.yml \
            -i ansible/hosts \
            --extra-vars "microblog_version=${DOCKER_TAG}"
        env:
          DOCKER_TAG: ${{ inputs.docker_tag }}