name: Security Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Test Dependencies
        run: make install-test

      - name: Run Bandit (SAST)
        run: make bandit

      - name: Run Trivy (filesystem + image scan)
        run: make security-scan

      - name: Run Dockle scan
        run: make dockle